[versions]

coroutinesVersion = { strictly = "1.8.0"   }
dateTimeVersion   = { strictly = "0.5.0"   }
dokkaVersion      = { strictly = "1.9.20"  }
jupiterVersion    = { strictly = "5.10.0"  }
kodeinVersion     = { strictly = "7.21.1"  }
kotlinVersion     = { strictly = "2.1.10"  }
koverVersion      = { strictly = "0.9.1"   }
logbackVersion    = { strictly = "1.4.11"  }
measuredVersion   = { strictly = "0.4.2"   }
mockkVersion      = { strictly = "1.13.13" }
skikoVersion      = { strictly = "0.9.2"   }
slf4jVersion      = { strictly = "2.0.9"   }
kxBrowserVersion  = { strictly = "0.3"     }
nmcpVersion       = { strictly = "1.0.2"   }

[libraries]

coroutines-core   = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core",  version.ref = "coroutinesVersion" }
coroutines-swing  = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutinesVersion" }
coroutines-test   = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test",  version.ref = "coroutinesVersion" }
datetime          = { module = "org.jetbrains.kotlinx:kotlinx-datetime",         version.ref = "dateTimeVersion"   }
junit-jupiter     = { module = "org.junit.jupiter:junit-jupiter",                version.ref = "jupiterVersion"    }
kodein-di         = { module = "org.kodein.di:kodein-di",                        version.ref = "kodeinVersion"     }
logback-classic   = { module = "ch.qos.logback:logback-classic",                 version.ref = "logbackVersion"    }
measured          = { module = "io.nacular.measured:measured",                   version.ref = "measuredVersion"   }
mockk             = { module = "io.mockk:mockk",                                 version.ref = "mockkVersion"      }
slf4j-api         = { module = "org.slf4j:slf4j-api",                            version.ref = "slf4jVersion"      }
kotlinx-browser   = { module = "org.jetbrains.kotlinx:kotlinx-browser",          version.ref = "kxBrowserVersion"  }

[plugins]

dokka             = { id = "org.jetbrains.dokka",                                version.ref = "dokkaVersion"      }
kover             = { id = "org.jetbrains.kotlinx.kover",                        version.ref = 'koverVersion'      }
nmcp              = { id = "com.gradleup.nmcp",                                  version.ref = "nmcpVersion"       }
nmcp-aggregation  = { id = "com.gradleup.nmcp.aggregation",                      version.ref = "nmcpVersion"       }

[bundles]

test-libs         = ["mockk", "slf4j-api", "junit-jupiter", "logback-classic"]
